#!/usr/bin/env bb

(ns swarm-handoff
  (:require [babashka.fs :as fs]
            [clojure.java.shell :refer [sh]]
            [squad-config :as cfg]
            [clojure.string :as str]))

(def usage-text
  (str "Usage:\n"
       "  swarm_handoff.sh\n"
       "  swarm_handoff.sh --review-decision accepted\n"
       "  swarm_handoff.sh <draft-file>\n"
       "  swarm_handoff.sh --help\n\n"
       "No file: fill the assignment result-handoff.draft from HEAD and queue it.\n"
       "A path is for note handoffs and odd cases.\n\n"
       "Draft formats:\n\n"
       "type: git_handoff\n"
       "to: <role>[,<role>...]\n"
       "priority: NN\n"
       "task: <short-stable-task-name>\n"
       "commit: <10-char-commit-abbrev>\n"
       "assignment: <assignment-id>\n"
       "template: <role-template>\n"
       "artifacts: <comma-separated-paths-or-none>\n"
       "review_decision: accepted or changes-requested  # review assignments only\n\n"
       "type: note\n"
       "to: <role>[,<role>...]\n"
       "priority: NN\n"
       "message: <one line, max 80 chars>"))

(def reserved-fields #{"id" "from" "role" "recipient" "created_at" "enqueued_at" "dequeued_at" "completed_at"})
(def allowed-fields #{"type" "to" "priority" "task" "commit" "assignment" "template" "artifacts" "review_decision" "message"})
(def allowed-types #{"git_handoff" "note"})

(defn usage []
  (binding [*out* *err*]
    (println usage-text)))

(defn exit! [status message]
  (binding [*out* *err*]
    (when message
      (println message)))
  (System/exit status))

(defn command
  ([dir & args]
   (let [result (apply sh (concat args [:dir (str dir)]))]
     result)))

(defn git-root []
  (let [result (command "." "git" "rev-parse" "--show-toplevel")]
    (when (zero? (:exit result))
      (str/trim (:out result)))))

(defn git-common-dir []
  (let [result (command "." "git" "rev-parse" "--git-common-dir")]
    (when (zero? (:exit result))
      (let [path (str/trim (:out result))]
        (if (fs/absolute? path)
          (str (fs/path path))
          (str (fs/absolutize path)))))))

(defn project-root []
  (or (cfg/project-root)
      (exit! 1 "Cannot find SwarmForge project root")))

(defn roles-file []
  (fs/path (project-root) ".swarmforge" "roles.tsv"))

(defn role-known? [role]
  (some (fn [line]
          (= role (first (str/split line #"\t"))))
        (str/split-lines (slurp (str (roles-file))))))

(defn sender-role []
  (if-let [role (not-empty (System/getenv "SWARMFORGE_ROLE"))]
    role
    (exit! 1 "Set SWARMFORGE_ROLE.")))

(defn state-dir []
  (fs/path (System/getProperty "user.dir") ".swarmforge" "handoffs"))

(defn timestamp []
  (.format java.time.format.DateTimeFormatter/ISO_INSTANT
           (java.time.Instant/now)))

(defn id-timestamp []
  (.format (java.time.format.DateTimeFormatter/ofPattern "yyyyMMdd'T'HHmmss'Z'")
           (.atZone (java.time.Instant/now) java.time.ZoneOffset/UTC)))

(defn valid-priority? [priority]
  (boolean (re-matches #"[0-9][0-9]" priority)))

(defn body-line-error [line-no line]
  (when-not (str/blank? line)
    (format "Line %d: draft handoffs may contain headers only; payloads are generated by swarm_handoff.sh." line-no)))

(def header-error-rules
  [[(fn [_ _ field value] (or (str/blank? field) (str/blank? value)))
    (fn [line-no _ _ _] (format "Line %d: field and value must both be non-empty." line-no))]
   [(fn [_ _ field _] (reserved-fields field))
    (fn [line-no _ field _] (format "Line %d: header '%s' is reserved and must not be written by agents." line-no field))]
   [(fn [_ _ field _] (not (allowed-fields field)))
    (fn [line-no _ field _] (format "Line %d: unknown header '%s'." line-no field))]
   [(fn [_ headers field _] (contains? headers field))
    (fn [line-no _ field _] (format "Line %d: duplicate header '%s'." line-no field))]])

(defn header-field-error [line-no headers field value]
  (some (fn [[predicate message]]
          (when (predicate line-no headers field value)
            (message line-no headers field value)))
        header-error-rules))

(defn header-line-error [line-no headers line]
  (if-not (str/includes? line ": ")
    (format "Line %d: expected 'field: value'." line-no)
    (let [[field value] (str/split line #": " 2)]
      (header-field-error line-no headers field value))))

(defn apply-header-line [state line-no line]
  (if-let [error (header-line-error line-no (:headers state) line)]
    (update state :errors conj error)
    (let [[field value] (str/split line #": " 2)]
      (-> state
          (assoc-in [:headers field] value)
          (update :ordered conj field)))))

(defn apply-draft-line [state [index line]]
  (let [line-no (inc index)]
    (cond
      (:body-seen? state)
      (cond-> state
        (body-line-error line-no line) (update :errors conj (body-line-error line-no line)))
      (str/blank? line)
      (assoc state :body-seen? true)
      :else
      (apply-header-line state line-no line))))

(defn parse-draft [draft]
  (select-keys
   (reduce apply-draft-line
           {:body-seen? false :headers {} :ordered [] :errors []}
           (map-indexed vector (str/split-lines (slurp (str draft)))))
   [:headers :ordered :errors]))

(defn recipient-errors [seen recipient]
  (cond-> []
    (str/blank? recipient)
    (conj "Header 'to' contains an empty recipient.")
    (str/includes? recipient "_")
    (conj (format "Recipient role '%s' is invalid; role names may not contain underscores." recipient))
    (contains? seen recipient)
    (conj (format "Duplicate recipient '%s'." recipient))
    (and (not (str/blank? recipient)) (not (role-known? recipient)))
    (conj (format "Unknown recipient role '%s'." recipient))))

(defn validate-recipient-list [recipients]
  (:errors
   (reduce (fn [{:keys [seen] :as state} recipient]
             (-> state
                 (update :errors into (recipient-errors seen recipient))
                 (update :seen conj recipient)))
           {:seen #{} :errors []}
           recipients)))

(defn validate-recipients [to]
  (if (str/blank? to)
    [[] []]
    (let [recipients (str/split to #"," -1)]
      [recipients (validate-recipient-list recipients)])))

(defn canonical-commit [commit]
  (let [matches (-> (command "." "git" "rev-parse" (str "--disambiguate=" commit))
                    :out
                    str/split-lines
                    vec)]
    (cond
      (not= 1 (count matches))
      [nil (format "Header 'commit' must resolve to exactly one Git object; '%s' matched %d." commit (count matches))]

      :else
      (let [object (first matches)
            object-type (str/trim (:out (command "." "git" "cat-file" "-t" object)))]
        (if (= "commit" object-type)
          [(str/trim (:out (command "." "git" "rev-parse" "--short=10" object))) nil]
          [nil (format "Header 'commit' must resolve to a commit; '%s' resolves to '%s'." commit object-type)])))))

(def fields-by-type
  {"git_handoff" #{"type" "to" "priority" "task" "commit" "assignment" "template" "artifacts" "review_decision"}
   "note" #{"type" "to" "priority" "message"}})

(defn allowed-for-type? [type field]
  (boolean (contains? (get fields-by-type type #{}) field)))

(defn field-errors [type ordered]
  (vec
   (for [field ordered
         :when (and type (not (allowed-for-type? type field)))]
     (format "Header '%s' is not allowed for type '%s'." field type))))

(defn required-header-errors [type to priority]
  (cond-> []
    (str/blank? type) (conj "Missing required header 'type'.")
    (str/blank? to) (conj "Missing required header 'to'.")
    (str/blank? priority) (conj "Missing required header 'priority'.")))

(defn type-errors [type]
  (when (and (not (str/blank? type)) (not (allowed-types type)))
    [(format "Header 'type' must be one of git_handoff or note; got '%s'." type)]))

(defn priority-errors [priority]
  (when (and (not (str/blank? priority)) (not (valid-priority? priority)))
    [(format "Header 'priority' must be two digits from 00 to 99; got '%s'." priority)]))

(defn base-errors [type to priority]
  (vec (concat (required-header-errors type to priority)
               (type-errors type)
               (priority-errors priority))))

(defn git-commit-result [type commit]
  (if (= "git_handoff" type)
    (cond
      (str/blank? commit) [nil "Missing required header 'commit' for git_handoff."]
      (not (re-matches #"[0-9a-fA-F]{10}" commit))
      [nil (format "Header 'commit' must be exactly 10 hexadecimal characters; got '%s'." commit)]
      :else (canonical-commit commit))
    [nil nil]))

(defn length-error [field label value]
  (when (> (count (or value "")) 80)
    [(format "Header '%s' must be no longer than 80 characters; got %d." label (count value))]))

(defn git-task-errors [type task-name]
  (when (= "git_handoff" type)
    (vec (concat (when (str/blank? task-name)
                   ["Missing required header 'task' for git_handoff."])
                 (length-error "task" "task" task-name)))))

(defn git-manifest-errors [type headers]
  (when (= "git_handoff" type)
    (vec
     (for [field ["assignment" "template" "artifacts"]
           :when (str/blank? (get headers field))]
       (format "Missing required header '%s' for git_handoff result manifest." field)))))

(def hardener-forbidden-root-files
  "Hardener must not thrash root build/lock manifests (merge conflicts)."
  #{"bb.edn" "deps.edn" "package.json" "package-lock.json"
    "Cargo.toml" "go.mod" "pom.xml" "build.gradle" "Makefile"
    "project.clj" "shadow-cljs.edn"})

(defn commit-changed-paths
  "Paths changed in commit (full hash or 10-char abbrev)."
  [commit]
  (when-not (str/blank? commit)
    (let [result (command "." "git" "diff-tree" "--no-commit-id" "--name-only" "-r" commit)]
      (when (zero? (:exit result))
        (->> (str/split-lines (:out result))
             (remove str/blank?)
             vec)))))

(defn hardener-root-tooling-errors
  "Reject hardener git_handoffs whose commit touches denylisted root files."
  [headers canonical-commit]
  (when (and (= "git_handoff" (get headers "type"))
             (= "hardener" (get headers "template"))
             (not (str/blank? canonical-commit)))
    (let [paths (or (commit-changed-paths canonical-commit) [])
          hits (filter (fn [p]
                         (and (not (str/includes? p "/"))
                              (contains? hardener-forbidden-root-files p)))
                       paths)]
      (when (seq hits)
        [(str "Hardener commits must not change root tooling files: "
              (str/join ", " (sort hits))
              ". Prefer bb/tasks/, src/, test/, acceptance/; hand back a blocker if root tooling is required.")]))))

(defn git-field-errors [type commit task-name commit-error]
  (vec
   (concat (git-task-errors type task-name)
           (when (and (not= "git_handoff" type) (not (str/blank? commit)))
             ["Header 'commit' is only allowed for git_handoff."])
           (when (and (not= "git_handoff" type) (not (str/blank? task-name)))
             ["Header 'task' is only allowed for git_handoff."])
           (when commit-error [commit-error]))))

(defn note-message-errors [type note-message]
  (when (= "note" type)
    (vec (concat (when (str/blank? note-message)
                   ["Missing required header 'message' for note."])
                 (length-error "message" "message" note-message)))))

(defn note-field-errors [type note-message]
  (vec
   (concat (note-message-errors type note-message)
           (when (and (not= "note" type) (not (str/blank? note-message)))
             ["Header 'message' is only allowed for note."]))))

(defn validate [headers ordered]
  (let [type (get headers "type")
        to (get headers "to")
        priority (get headers "priority")
        commit (get headers "commit")
        task-name (get headers "task")
        note-message (get headers "message")
        [recipients recipient-errors] (validate-recipients to)
        [canonical commit-error] (git-commit-result type commit)]
    {:recipients recipients
     :canonical-commit canonical
     :errors (vec (concat (base-errors type to priority)
                          recipient-errors
                          (field-errors type ordered)
                          (git-field-errors type commit task-name commit-error)
                          (git-manifest-errors type headers)
                          (hardener-root-tooling-errors headers canonical)
                          (note-field-errors type note-message)))}))

(declare acquire-sequence-lock! write-next-sequence!)

(defn next-sequence []
  (let [dir (state-dir)
        seq-file (fs/path dir "sequence")
        lock-dir (fs/path dir "sequence.lock")]
    (fs/create-dirs dir)
    (acquire-sequence-lock! lock-dir)
    (try
      (write-next-sequence! seq-file)
      (finally
        (fs/delete lock-dir)))))

(defn acquire-sequence-lock! [lock-dir]
  (loop []
    (if (try
          (fs/create-dir lock-dir)
          true
          (catch java.nio.file.FileAlreadyExistsException _
            false))
      nil
      (do
        (Thread/sleep 50)
        (recur)))))

(defn read-sequence-value [seq-file]
  (if (fs/exists? seq-file)
    (try
      (Long/parseLong (str/trim (slurp (str seq-file))))
      (catch Exception _ 0))
    0))

(defn write-next-sequence! [seq-file]
  (let [formatted (format "%06d" (inc (read-sequence-value seq-file)))]
    (spit (str seq-file) (str formatted "\n"))
    formatted))

(defn body [type sender canonical-commit note-message]
  (case type
    "git_handoff" (str "Re-read your role and constitution.\n\nmerge_and_process " sender " " canonical-commit)
    "note" (str "Re-read your role and constitution.\n\n" note-message)))

(defn handoff-files-in [dir]
  (when (fs/exists? dir)
    (->> (fs/list-dir dir)
         (filter #(and (fs/regular-file? %)
                       (str/ends-with? (fs/file-name %) ".handoff"))))))

(defn existing-handoff-files []
  (mapcat handoff-files-in
          [(fs/path (state-dir) "outbox")
           (fs/path (state-dir) "sent")
           (fs/path (state-dir) "failed")]))

(defn read-header [file field]
  (let [prefix (str field ": ")]
    (some (fn [line]
            (when (str/starts-with? line prefix)
              (subs line (count prefix))))
          (take-while #(not (str/blank? %))
                      (str/split-lines (slurp (str file)))))))

(defn duplicate-git-handoff [sender recipients headers canonical-commit]
  (when (= "git_handoff" (get headers "type"))
    (let [to (str/join "," recipients)
          task (get headers "task")]
      (some (fn [file]
              (when (and (= "git_handoff" (read-header file "type"))
                         (= sender (read-header file "from"))
                         (= to (read-header file "to"))
                         (= task (read-header file "task"))
                         (= canonical-commit (read-header file "commit")))
                file))
            (existing-handoff-files)))))

(defn write-handoff! [{:keys [headers recipients canonical-commit sender]}]
  (let [timestamp-id (id-timestamp)
        created-at (timestamp)
        sequence (next-sequence)
        id (str timestamp-id "_" sequence "_from_" sender)
        recipient-slug (str/join "_" recipients)
        priority (get headers "priority")
        type (get headers "type")
        filename (str priority "_" timestamp-id "_" sequence "_from_" sender "_to_" recipient-slug ".handoff")
        outbox-dir (fs/path (state-dir) "outbox")
        tmp-dir (fs/path outbox-dir "tmp")
        tmp-file (fs/path tmp-dir (str filename ".tmp"))
        outbox-file (fs/path outbox-dir filename)
        handoff-body (body type sender canonical-commit (get headers "message"))
        lines (cond-> [(str "id: " id)
                       (str "from: " sender)
                       (str "to: " (str/join "," recipients))
                       (str "priority: " priority)
                       (str "type: " type)]
                (= "git_handoff" type)
                (conj (str "role: " sender)
                      (str "task: " (get headers "task"))
                      (str "commit: " canonical-commit)
                      (str "assignment: " (get headers "assignment"))
                      (str "agent: " sender)
                      (str "template: " (get headers "template"))
                      (str "artifacts: " (get headers "artifacts")))
                (and (= "git_handoff" type)
                     (not (str/blank? (get headers "review_decision"))))
                (conj (str "review_decision: " (get headers "review_decision")))
                (= "note" type)
                (conj (str "message: " (get headers "message")))
                true
                (conj (str "created_at: " created-at)
                      ""
                      handoff-body))]
    (doseq [dir [tmp-dir outbox-dir (fs/path (state-dir) "sent") (fs/path (state-dir) "failed")]]
      (fs/create-dirs dir))
    (spit (str tmp-file) (str (str/join "\n" lines) "\n"))
    (fs/move tmp-file outbox-file)
    outbox-file))

(defn error-report [draft errors]
  (binding [*out* *err*]
    (println "HANDOFF INVALID:" (str draft))
    (println)
    (println "Errors:")
    (doseq [error errors]
      (println "-" error))
    (println)
    (println usage-text)))

(defn help-arg? [args]
  (boolean (some #{"--help" "-h"} args)))

(defn parse-handoff-args [args]
  (let [args (vec args)]
    (cond
      (help-arg? args) {:help? true}
      (empty? args) {:assignment? true}
      (and (= "--review-decision" (first args)) (second args) (nil? (get args 2)))
      {:assignment? true :review-decision (second args)}
      (= 1 (count args)) {:draft (fs/path (first args))}
      :else {:error true})))

(defn ensure-draft-file! [draft]
  (when-not (fs/regular-file? draft)
    (exit! 1 (str "Draft file not found: " draft))))

(defn ensure-known-sender! [sender]
  (when-not (role-known? sender)
    (exit! 1 (str "Unknown sender role: " sender))))

(defn checked-draft [draft]
  (let [{:keys [headers ordered errors]} (parse-draft draft)
        validation (validate headers ordered)
        all-errors (vec (concat errors (:errors validation)))]
    (when (seq all-errors)
      (error-report draft all-errors)
      (System/exit 2))
    {:headers headers :validation validation}))

(defn queue-handoff!
  ([draft sender checked]
   (queue-handoff! draft sender checked false))
  ([draft sender {:keys [headers validation]} keep-draft?]
   (let [recipients (:recipients validation)
         canonical-commit (:canonical-commit validation)
         finish! (fn [line]
                   (when-not keep-draft?
                     (fs/delete draft))
                   (println line))]
     (if-let [existing (duplicate-git-handoff sender recipients headers canonical-commit)]
       (finish! (str "HANDOFF EXISTING: " existing))
       (let [outbox-file (write-handoff! {:headers headers
                                          :recipients recipients
                                          :canonical-commit canonical-commit
                                          :sender sender})]
         (finish! (str "HANDOFF QUEUED: " outbox-file)))))))

(defn read-kv [file field]
  (when (fs/regular-file? file)
    (read-header file field)))

(defn head-commit []
  (let [result (command "." "git" "rev-parse" "--short=10" "HEAD")]
    (when-not (zero? (:exit result))
      (exit! 1 "Cannot read HEAD commit."))
    (str/trim (:out result))))

(defn head-artifacts []
  (let [result (command "." "git" "diff-tree" "--no-commit-id" "--name-only" "-r" "HEAD")
        paths (->> (str/split-lines (or (:out result) ""))
                   (remove str/blank?))]
    (if (seq paths)
      (str/join "," paths)
      "none")))

(defn write-draft-headers! [draft headers ordered]
  (let [fields (distinct (concat ordered ["commit" "artifacts" "review_decision"]))
        lines (keep (fn [field]
                      (when-let [value (get headers field)]
                        (str field ": " value)))
                    fields)]
    (spit (str draft) (str (str/join "\n" lines) "\n"))))

(defn fill-assignment-draft! [draft commit artifacts review-decision]
  (let [{:keys [headers ordered]} (parse-draft draft)
        headers (-> headers
                    (assoc "commit" commit)
                    (assoc "artifacts" artifacts)
                    (cond-> (not (str/blank? review-decision))
                      (assoc "review_decision" review-decision)))]
    (write-draft-headers! draft headers ordered)
    draft))

(defn reviewer-draft? [headers]
  (contains? #{"code-reviewer" "architect"} (get headers "template")))

(defn ensure-review-decision! [headers]
  (when (and (reviewer-draft? headers)
             (not (#{"accepted" "changes-requested"} (get headers "review_decision"))))
    (exit! 2 "Review assignments require --review-decision accepted or changes-requested.")))

(defn assignment-git-handoff! [review-decision]
  (let [sender (sender-role)
        root (project-root)
        task-id (read-kv (fs/path root ".squad" "agents" sender "metadata") "task_id")
        draft (when task-id
                (fs/path root ".squad" "assignments" task-id "result-handoff.draft"))]
    (when (str/blank? task-id)
      (exit! 1 "Agent metadata task_id is missing."))
    (ensure-draft-file! draft)
    (ensure-known-sender! sender)
    (fill-assignment-draft! draft (head-commit) (head-artifacts) review-decision)
    (let [checked (checked-draft draft)]
      (ensure-review-decision! (:headers checked))
      (queue-handoff! draft sender checked true))))

(defn -main [& args]
  (let [parsed (parse-handoff-args args)]
    (cond
      (:help? parsed) (do (usage) (System/exit 0))
      (:error parsed) (do (usage) (System/exit 1))
      (:draft parsed)
      (let [draft (:draft parsed)
            sender (sender-role)]
        (ensure-draft-file! draft)
        (ensure-known-sender! sender)
        (queue-handoff! draft sender (checked-draft draft)))
      :else
      (assignment-git-handoff! (:review-decision parsed)))))

(when (= *file* (System/getProperty "babashka.file"))
  (apply -main *command-line-args*))
